# Generated by Django 5.0.2 on 2024-03-05 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label1', models.CharField(default='', max_length=100)),
                ('score1_weight', models.ImageField(default=0, upload_to='')),
                ('label2', models.CharField(default='', max_length=100)),
                ('score2_weight', models.ImageField(default=0, upload_to='')),
                ('label3', models.CharField(default='', max_length=100)),
                ('score3_weight', models.ImageField(default=0, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('activity_start_time', models.DateTimeField(blank=True, null=True)),
                ('activity_end_time', models.DateTimeField(blank=True, null=True)),
                ('sign_up_start_time', models.DateTimeField(blank=True, null=True)),
                ('sign_up_end_time', models.DateTimeField(blank=True, null=True)),
                ('score_label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.scorelabel')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.IntegerField(default=0)),
                ('score2', models.IntegerField(default=0)),
                ('score3', models.IntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.activity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
            ],
            options={
                'unique_together': {('student', 'activity')},
            },
        ),
    ]
