# Generated by Django 5.0.2 on 2024-03-05 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='score_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_label', to='myapp.scorelabel'),
        ),
        migrations.AlterField(
            model_name='scorelabel',
            name='score1_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scorelabel',
            name='score2_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scorelabel',
            name='score3_weight',
            field=models.IntegerField(default=0),
        ),
    ]
