# Generated by Django 5.0.2 on 2024-03-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_activity_score_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='score_open_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
