# Generated by Django 5.0.2 on 2024-03-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_activity_score_open_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='sign_up_print_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
