# Generated by Django 5.0.2 on 2024-03-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_activity_activity_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='score_min',
            field=models.IntegerField(default=0),
        ),
    ]
