# Generated by Django 5.0.2 on 2024-03-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_activity_score_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='score_min',
            field=models.FloatField(default=0),
        ),
    ]
