# Generated by Django 5.0.2 on 2024-03-28 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_activity_score_min'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorelabel',
            name='score1_weight',
        ),
        migrations.RemoveField(
            model_name='scorelabel',
            name='score2_weight',
        ),
        migrations.RemoveField(
            model_name='scorelabel',
            name='score3_weight',
        ),
    ]
