# Generated by Django 5.0.2 on 2024-04-11 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_score_score1_alter_score_score2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='sign_up_print_end_time',
        ),
    ]
