# Generated by Django 5.0.2 on 2024-08-05 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_activity_sign_up_print_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoluntaryYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VoluntarySchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('academic', models.CharField(default='', max_length=100)),
                ('category', models.CharField(default='', max_length=100)),
                ('department', models.CharField(default='', max_length=100)),
                ('quota', models.IntegerField(default=0)),
                ('code', models.CharField(default='', max_length=100)),
                ('voluntary_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.voluntaryyear')),
            ],
        ),
    ]
