# Generated by Django 5.0.2 on 2024-08-06 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_voluntaryyear_voluntaryschool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntaryschool',
            name='voluntary_year',
        ),
        migrations.AddField(
            model_name='voluntaryschool',
            name='activity',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='myapp.activity'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='VoluntaryYear',
        ),
    ]
