# Generated by Django 5.0.2 on 2024-03-05 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='activity',
            field=models.ManyToManyField(to='myapp.activity'),
        ),
        migrations.AddField(
            model_name='student',
            name='graduated_school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.school'),
        ),
    ]
