# Generated by Django 5.0.2 on 2024-03-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='military_type',
            field=models.IntegerField(choices=[(1, ''), (2, '一類'), (3, '二類')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='school_notes',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
