# Generated by Django 5.0.2 on 2024-03-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_student_graduated_year_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='military_service_years_int',
            field=models.IntegerField(),
        ),
    ]
