# Generated by Django 5.0.2 on 2024-03-14 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_student_military_service_years_int'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='student',
            name='join_time',
        ),
    ]
