# Generated by Django 5.0.2 on 2024-03-14 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_activity_score_open_time'),
        ('user', '0010_remove_student_activity_remove_student_join_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_time', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.activity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='activity',
            field=models.ManyToManyField(related_name='student', through='user.ActivityStudents', to='myapp.activity'),
        ),
    ]
