# Generated by Django 5.0.2 on 2024-03-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_activitystudents_student_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sex',
            new_name='gender',
        ),
        migrations.AlterField(
            model_name='student',
            name='identity_back',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='identity_front',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
