# Generated by Django 5.0.2 on 2024-03-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_activitystudents_checked_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitystudents',
            name='checked_number',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
