# Generated by Django 5.0.2 on 2024-03-27 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_activity_score_min'),
        ('user', '0016_alter_activitystudents_checked_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='graduated_school',
            field=models.ForeignKey(default='請選擇', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.school'),
        ),
    ]
