# Generated by Django 5.0.2 on 2024-03-29 10:29

import django.core.validators
import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_student_graduated_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='identity_back',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y-%m-%d', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), user.models.file_size_check]),
        ),
        migrations.AlterField(
            model_name='student',
            name='identity_front',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y-%m-%d', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), user.models.file_size_check]),
        ),
    ]
