# Generated by Django 5.0.2 on 2024-04-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_student_identity_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='military_type',
            field=models.IntegerField(choices=[(1, ''), (2, '榮民'), (3, '二類')], default=1),
        ),
    ]
