# Generated by Django 5.0.2 on 2024-08-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_student_military_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='graduated_educational',
            field=models.IntegerField(choices=[(1, '高中'), (2, '專科'), (3, '大學')], default=1),
        ),
    ]
