# Generated by Django 5.0.2 on 2024-08-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_student_graduated_educational'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='military_card_type',
            field=models.IntegerField(choices=[(1, '權益卡'), (2, '榮民證')], default=1),
        ),
    ]
